"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";

export function AuthForm({ mode }: { mode: "login" | "register" | "forgot" | "reset" }) {
  const router = useRouter(); const [status, setStatus] = useState(""); const config = { login: ["Chào mẹ quay lại", "Đăng nhập để theo dõi đơn hàng và lưu những điều mẹ yêu thích."], register: ["Tạo tài khoản An An", "Chỉ một phút để mua sắm thuận tiện và nhận ưu đãi riêng."], forgot: ["Quên mật khẩu?", "Nhập email, An An sẽ gửi đường dẫn đặt lại mật khẩu."], reset: ["Đặt mật khẩu mới", "Mật khẩu nên có ít nhất 8 ký tự, gồm chữ và số."] }[mode];
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!event.currentTarget.reportValidity()) return; setStatus("Đang xử lý..."); setTimeout(() => { if (mode === "login" || mode === "reset") router.push("/account"); else if (mode === "register") router.push("/login?registered=1"); else setStatus("Đã gửi hướng dẫn. Mẹ vui lòng kiểm tra hộp thư và thư rác."); }, 500); };
  return <><p className="text-xs font-semibold tracking-[.2em] text-[#c26b77]">TÀI KHOẢN AN AN</p><h1 className="mt-3 font-serif text-4xl">{config[0]}</h1><p className="mt-3 leading-7 text-[#6b5e5e]">{config[1]}</p><form className="mt-8 space-y-5" onSubmit={submit}>{mode === "register" && <Input label="Họ và tên" name="name" autoComplete="name"/>}<Input label="Email" name="email" type="email" autoComplete="email"/>{(mode === "login" || mode === "register") && <Input label="Mật khẩu" name="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"}/>} {mode === "reset" && <><Input label="Mật khẩu mới" name="password" type="password" autoComplete="new-password"/><Input label="Nhập lại mật khẩu" name="confirmPassword" type="password" autoComplete="new-password"/></>}{mode === "register" && <label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" required/><span>Tôi đồng ý với điều khoản sử dụng và chính sách bảo mật.</span></label>}{mode === "login" && <div className="text-right"><a className="text-sm text-[#ce7a85] underline" href="/forgot-password">Quên mật khẩu?</a></div>}<Button className="w-full">{mode === "login" ? "Đăng nhập" : mode === "register" ? "Tạo tài khoản" : mode === "forgot" ? "Gửi hướng dẫn" : "Lưu mật khẩu mới"}</Button>{status && <p className="rounded-xl bg-white p-3 text-sm text-[#536b57]" role="status">{status}</p>}</form><p className="mt-7 text-center text-sm text-[#6b5e5e]">{mode === "login" ? <>Chưa có tài khoản? <a className="font-semibold text-[#ce7a85] underline" href="/register">Đăng ký ngay</a></> : <>Đã có tài khoản? <a className="font-semibold text-[#ce7a85] underline" href="/login">Đăng nhập</a></>}</p></>;
}
function Input({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="block text-sm font-medium">{label}<input className="mt-2 w-full rounded-xl border border-[#d9d0cb] bg-white px-4 py-3" required {...props}/></label>; }
