"use client";
import { useState } from "react";
import { ButtonLink } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/states";
import { money, products } from "@/lib/storefront/data";

const seed = [{ product: products[0], size: "M", color: "Be tự nhiên", quantity: 1 }, { product: products[2], size: "0–3M", color: "Trắng sữa", quantity: 1 }];
export function CartClient() {
  const [items, setItems] = useState(seed); const subtotal = items.reduce((sum, item) => sum + item.product.price * item.quantity, 0); const shipping = subtotal >= 699000 ? 0 : 30000;
  if (!items.length) return <EmptyState title="Giỏ hàng đang trống" description="Mẹ chưa thêm sản phẩm nào. Hãy khám phá những thiết kế dịu dàng của An An nhé."/>;
  const quantity = (index: number, next: number) => setItems((current) => next < 1 ? current.filter((_, i) => i !== index) : current.map((item, i) => i === index ? { ...item, quantity: next } : item));
  return <div className="grid gap-10 lg:grid-cols-[1fr_380px]"><section className="divide-y divide-[#e4dad5]">{items.map((item, index) => <article className="grid grid-cols-[110px_1fr] gap-5 py-6 first:pt-0 sm:grid-cols-[140px_1fr_auto]" key={`${item.product.id}-${item.size}`}><img className="aspect-[4/5] size-full rounded-2xl object-cover" src={item.product.image} alt={item.product.name}/><div><h2 className="font-semibold">{item.product.name}</h2><p className="mt-2 text-sm text-[#776b65]">{item.color} · Size {item.size}</p><strong className="mt-3 block">{money(item.product.price)}</strong><div className="mt-4 inline-flex items-center rounded-full border"><button className="size-10" onClick={() => quantity(index, item.quantity - 1)} aria-label="Giảm số lượng">−</button><span className="w-8 text-center" aria-live="polite">{item.quantity}</span><button className="size-10" onClick={() => quantity(index, item.quantity + 1)} aria-label="Tăng số lượng">+</button></div></div><button className="col-start-2 self-start text-sm text-[#8a493d] underline sm:col-start-auto" onClick={() => quantity(index, 0)}>Xóa</button></article>)}</section><aside className="h-fit rounded-3xl bg-white p-6 shadow-sm lg:sticky lg:top-24"><h2 className="font-serif text-2xl">Tóm tắt đơn hàng</h2><dl className="mt-6 space-y-4 text-sm"><div className="flex justify-between"><dt>Tạm tính</dt><dd>{money(subtotal)}</dd></div><div className="flex justify-between"><dt>Vận chuyển</dt><dd>{shipping ? money(shipping) : "Miễn phí"}</dd></div><div className="flex justify-between border-t pt-4 text-base font-semibold"><dt>Tổng cộng</dt><dd>{money(subtotal + shipping)}</dd></div></dl>{shipping > 0 && <p className="mt-5 rounded-xl bg-[#f3e5de] p-4 text-sm">Mua thêm {money(699000 - subtotal)} để được miễn phí vận chuyển.</p>}<ButtonLink href="/checkout" className="mt-6 w-full">Tiến hành thanh toán</ButtonLink><p className="mt-4 text-center text-xs text-[#776b65]">Giá cuối cùng sẽ được xác nhận an toàn tại máy chủ.</p></aside></div>;
}
