"use client";

import { useEffect, useState } from "react";
import { ButtonLink } from "@/components/ui/button";
import { EmptyState, PageSkeleton } from "@/components/ui/states";
import { apiRequest, type ApiCart } from "@/lib/storefront/api";
import { money, products } from "@/lib/storefront/data";

export function CartClientV2() {
  const [cart, setCart] = useState<ApiCart | null>(null);
  const [error, setError] = useState("");
  const [pendingId, setPendingId] = useState("");
  useEffect(() => { apiRequest<ApiCart>("/api/cart", { method: "GET" }).then(setCart).catch((reason) => { setError(reason instanceof Error ? reason.message : "Không thể tải giỏ hàng."); setCart({ items: [], subtotal: 0 }); }); }, []);

  const update = async (itemId: string, quantity: number) => { setPendingId(itemId); setError(""); try { setCart(await apiRequest<ApiCart>("/api/cart", { method: "PATCH", body: JSON.stringify({ itemId, quantity }) })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể cập nhật giỏ hàng."); } finally { setPendingId(""); } };
  const remove = async (itemId: string) => { setPendingId(itemId); setError(""); try { setCart(await apiRequest<ApiCart>(`/api/cart?itemId=${encodeURIComponent(itemId)}`, { method: "DELETE" })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể xóa sản phẩm."); } finally { setPendingId(""); } };

  if (!cart) return <PageSkeleton/>;
  if (!cart.items.length) return <div data-testid="cart-empty">{error && <p className="mx-auto max-w-xl rounded-xl bg-red-50 p-4 text-center text-sm text-red-800" role="alert">{error}</p>}<EmptyState title="Giỏ hàng đang trống" description="Mẹ chưa thêm sản phẩm nào. Hãy khám phá những thiết kế dịu dàng của An An nhé." actionHref="/products" action="Khám phá sản phẩm"/></div>;
  const shipping = cart.subtotal >= 699000 ? 0 : 30000;

  return <div className="grid gap-10 lg:grid-cols-[1fr_380px]" data-testid="cart-lines"><section aria-label="Sản phẩm trong giỏ">{error && <p className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-800" role="alert">{error}</p>}<div className="divide-y divide-[#e4dad5]">{cart.items.map((item) => { const fallback = products.find((product) => product.slug === item.product.slug); const image = item.product.imageUrl || fallback?.image; const busy = pendingId === item.id; return <article className="grid grid-cols-[96px_1fr] gap-4 py-6 first:pt-0 sm:grid-cols-[140px_1fr_auto] sm:gap-5" aria-busy={busy} key={item.id}>{image ? <img className="aspect-[4/5] size-full rounded-2xl object-cover" src={image} alt={item.product.name}/> : <div className="aspect-[4/5] rounded-2xl bg-[#faeff1]" aria-hidden/>}<div><h2 className="font-semibold"><a className="hover:underline" href={`/products/${item.product.slug}`}>{item.product.name}</a></h2><p className="mt-2 text-sm text-[#625853]">{item.variantName}</p><strong className="mt-3 block">{money(item.unitPrice)}</strong><div className="mt-4 inline-flex items-center rounded-xl border border-[#cbbfba]" aria-label={`Số lượng ${item.product.name}`}><button type="button" className="grid size-11 place-items-center" disabled={busy || item.quantity <= 1} onClick={() => update(item.id, item.quantity - 1)} aria-label={`Giảm số lượng ${item.product.name}`}>−</button><span className="min-w-10 text-center" aria-live="polite"><span className="sr-only">Số lượng: </span>{item.quantity}</span><button type="button" className="grid size-11 place-items-center" disabled={busy} onClick={() => update(item.id, item.quantity + 1)} aria-label={`Tăng số lượng ${item.product.name}`}>+</button></div><button type="button" className="ml-3 min-h-11 text-sm text-[#c26b77] underline" disabled={busy} onClick={() => remove(item.id)}>{busy ? "Đang cập nhật…" : "Xóa"}</button></div><strong className="hidden sm:block">{money(item.lineTotal)}</strong></article>; })}</div></section><aside className="h-fit rounded-3xl bg-white p-6 shadow-sm lg:sticky lg:top-24"><h2 className="font-serif text-2xl">Tóm tắt đơn hàng</h2><dl className="mt-6 space-y-4 text-sm"><div className="flex justify-between"><dt>Tạm tính</dt><dd>{money(cart.subtotal)}</dd></div><div className="flex justify-between"><dt>Vận chuyển</dt><dd>{shipping ? money(shipping) : "Miễn phí"}</dd></div><div className="flex justify-between border-t pt-4 text-base font-semibold"><dt>Tổng cộng dự kiến</dt><dd>{money(cart.subtotal + shipping)}</dd></div></dl>{shipping > 0 && <p className="mt-4 text-xs text-[#625853]">Mua thêm {money(699000 - cart.subtotal)} để được miễn phí vận chuyển.</p>}<ButtonLink href="/checkout" className="mt-6 w-full">Tiến hành thanh toán</ButtonLink><p className="mt-4 text-center text-xs text-[#625853]">Giá cuối cùng được đọc lại và xác nhận tại máy chủ.</p></aside></div>;
}
