"use client";
import { useState } from "react";
import { Button, ButtonLink } from "@/components/ui/button";
import { money } from "@/lib/storefront/data";
import type { Product } from "@/lib/storefront/types";

export function ProductDetail({ product }: { product: Product }) {
  const [image, setImage] = useState(0); const [size, setSize] = useState(""); const [color, setColor] = useState(product.colors[0]?.name ?? ""); const [quantity, setQuantity] = useState(1); const [message, setMessage] = useState("");
  const validate = () => { if (!size) { setMessage("Mẹ vui lòng chọn kích thước trước khi thêm vào giỏ."); return false; } setMessage("Đã thêm sản phẩm vào giỏ hàng mẫu."); return true; };
  return <div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><section><div className="aspect-[4/5] overflow-hidden rounded-3xl bg-[#eee6e1]"><img className="size-full object-cover" src={product.images[image] ?? product.image} alt={product.name}/></div><div className="mt-3 flex gap-3">{product.images.map((src, index) => <button className={`size-20 overflow-hidden rounded-xl border-2 ${image === index ? "border-[#713c33]" : "border-transparent"}`} onClick={() => setImage(index)} aria-label={`Xem ảnh ${index + 1}`} key={src}><img className="size-full object-cover" src={src} alt=""/></button>)}</div></section><section className="lg:sticky lg:top-24 lg:self-start"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#8a493d]">{product.categoryLabel}</p><div className="mt-3 flex items-start justify-between gap-5"><h1 className="font-serif text-4xl leading-tight">{product.name}</h1><button className="grid size-11 shrink-0 place-items-center rounded-full border text-xl" aria-label="Thêm vào yêu thích">♡</button></div><p className="mt-4 text-sm text-[#6d625d]">★ {product.rating} · <a href="#reviews" className="underline">{product.reviewCount} đánh giá</a></p><div className="mt-5 flex gap-3 text-xl"><strong>{money(product.price)}</strong>{product.compareAtPrice && <del className="text-base text-[#9b918c]">{money(product.compareAtPrice)}</del>}</div><p className="mt-6 leading-7 text-[#665a55]">{product.description}</p><fieldset className="mt-8"><legend className="font-semibold">Màu sắc <span className="font-normal text-[#776b65]">· {color}</span></legend><div className="mt-3 flex gap-3">{product.colors.map((item) => <button type="button" className={`size-10 rounded-full border-4 ${color === item.name ? "ring-2 ring-[#713c33] ring-offset-2" : ""}`} style={{ background: item.hex }} onClick={() => setColor(item.name)} aria-label={item.name} key={item.name}/>)}</div></fieldset><fieldset className="mt-8"><div className="flex justify-between"><legend className="font-semibold">Kích thước</legend><a href="#size-guide" className="text-sm text-[#713c33] underline">Hướng dẫn chọn size</a></div><div className="mt-3 grid grid-cols-4 gap-2">{product.sizes.map((item) => <button type="button" className={`min-h-13 rounded-xl border text-sm ${size === item.name ? "border-[#713c33] bg-[#f7eeea]" : "border-[#d9d0cb]"}`} onClick={() => { setSize(item.name); setMessage(""); }} key={item.name}>{item.name}</button>)}</div></fieldset>
<fieldset className="mt-8"><legend className="font-semibold">Số lượng</legend>
  <div className="mt-3 flex h-13 w-32 items-center rounded-xl border border-[#cbbfba] bg-white">
    <button type="button" className="flex h-full w-10 items-center justify-center text-xl text-[#713c33] hover:bg-[#f7eeea] rounded-l-xl transition-colors" onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Giảm số lượng">-</button>
    <input type="number" min="1" max="99" value={quantity} onChange={(e) => setQuantity(Math.max(1, parseInt(e.target.value) || 1))} className="h-full flex-1 text-center font-medium border-none p-0 focus:ring-0" aria-label="Số lượng" />
    <button type="button" className="flex h-full w-10 items-center justify-center text-xl text-[#713c33] hover:bg-[#f7eeea] rounded-r-xl transition-colors" onClick={() => setQuantity(quantity + 1)} aria-label="Tăng số lượng">+</button>
  </div>
</fieldset>
{message && <p className={`mt-4 rounded-xl px-4 py-3 text-sm ${message.startsWith("Đã") ? "bg-green-50 text-green-800" : "bg-red-50 text-red-800"}`} role="status">{message}</p>}<div className="mt-7 grid gap-3 sm:grid-cols-2"><Button className="border border-[#713c33] bg-transparent text-[#713c33] hover:bg-[#f7eeea]" onClick={validate}>Thêm vào giỏ</Button><ButtonLink href={size ? `/checkout?buyNow=${product.sizes.find(s => s.name === size)?.variantId}&qty=${quantity}` : "#chon-size"} className="w-full" >Mua ngay</ButtonLink></div><ul className="mt-7 grid gap-3 border-y border-[#e2d8d3] py-5 text-sm text-[#665a55]"><li>✓ Giao trong 2–4 ngày</li><li>✓ Miễn phí vận chuyển từ 699.000đ</li><li>✓ Hỗ trợ đổi size trong 14 ngày</li></ul><div className="mt-5 divide-y" id="size-guide"><details open className="py-4"><summary className="font-semibold">Chất liệu & bảo quản</summary><p className="mt-3 text-sm leading-6 text-[#665a55]">{product.material}. Giặt nhẹ bằng nước mát, phơi trong bóng râm.</p></details><details className="py-4"><summary className="font-semibold">Giai đoạn phù hợp</summary><p className="mt-3 text-sm text-[#665a55]">{product.stage}. Nếu nằm giữa hai size, mẹ ưu tiên size lớn hơn.</p></details></div></section></div>;
}
