"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { apiRequest, type ApiCart } from "@/lib/storefront/api";
import { money } from "@/lib/storefront/data";
import type { Product } from "@/lib/storefront/types";

export function ProductDetailIntegrated({ product }: { product: Product }) {
  const [image, setImage] = useState(0); const [size, setSize] = useState(""); const [color, setColor] = useState(product.colors[0]?.name ?? ""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  useEffect(() => { try { const current = JSON.parse(localStorage.getItem("anan_recent_products") ?? "[]") as string[]; localStorage.setItem("anan_recent_products", JSON.stringify([product.id, ...current.filter((id) => id !== product.id)].slice(0, 12))); } catch { localStorage.setItem("anan_recent_products", JSON.stringify([product.id])); } }, [product.id]);
  const add = async (buyNow = false) => { if (!size) { setError("Mẹ vui lòng chọn kích thước trước khi thêm vào giỏ."); return; } setPending(true); setError(""); setMessage(""); try { await apiRequest<ApiCart>("/api/cart", { method: "POST", body: JSON.stringify({ variantId: product.sizes.find((item) => item.name === size)?.variantId, quantity: 1 }) }); setMessage("Đã thêm sản phẩm vào giỏ hàng."); if (buyNow) window.location.assign("/checkout"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể thêm sản phẩm."); } finally { setPending(false); } };
  return <div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr]" data-testid="product-detail"><section><div className="aspect-[4/5] overflow-hidden rounded-3xl bg-[#faeff1]"><img className="size-full object-cover" src={product.images[image] ?? product.image} alt={product.name}/></div><div className="mt-3 flex gap-3">{product.images.map((src, index) => <button className={`size-20 overflow-hidden rounded-xl border-2 ${image === index ? "border-[#ce7a85]" : "border-transparent"}`} onClick={() => setImage(index)} aria-label={`Xem ảnh ${index + 1}`} key={src}><img className="size-full object-cover" src={src} alt=""/></button>)}</div></section><section className="lg:sticky lg:top-24 lg:self-start"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#c26b77]">{product.categoryLabel}</p><h1 className="mt-3 font-serif text-4xl leading-tight">{product.name}</h1><p className="mt-4 text-sm text-[#6b5e5e]">★ {product.rating} · {product.reviewCount} đánh giá</p><div className="mt-5 flex gap-3 text-xl"><strong>{money(product.price)}</strong>{product.compareAtPrice && <del className="text-base text-[#9b918c]">{money(product.compareAtPrice)}</del>}</div><p className="mt-6 leading-7 text-[#665a5a]">{product.description}</p><fieldset className="mt-8"><legend className="font-semibold">Màu sắc · <span className="font-normal">{color}</span></legend><div className="mt-3 flex gap-3">{product.colors.map((item) => <button type="button" className={`size-10 rounded-full border-4 ${color === item.name ? "ring-2 ring-[#ce7a85] ring-offset-2" : ""}`} style={{ background: item.hex }} onClick={() => setColor(item.name)} aria-label={item.name} key={item.name}/>)}</div></fieldset><fieldset className="mt-8" id="chon-size"><legend className="font-semibold">Kích thước</legend><div className="mt-3 grid grid-cols-4 gap-2">{product.sizes.map((item) => <button type="button" className={`min-h-13 rounded-xl border text-sm ${size === item.name ? "border-[#ce7a85] bg-[#fcf4f5]" : "border-[#d9d0cb]"}`} onClick={() => { setSize(item.name); setError(""); }} data-testid={`size-${item.name}`} key={item.name}>{item.name}</button>)}</div></fieldset>{error && <p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">{error}</p>}{message && <p className="mt-4 rounded-xl bg-green-50 px-4 py-3 text-sm text-green-800" role="status">{message}</p>}<div className="mt-7 grid gap-3 sm:grid-cols-2"><Button disabled={pending} data-testid="add-to-cart" className="border border-[#ce7a85] bg-transparent text-[#ce7a85] hover:bg-[#fcf4f5]" onClick={() => void add()}>{pending ? "Đang thêm..." : "Thêm vào giỏ"}</Button><Button disabled={pending} className="w-full" onClick={() => void add(true)}>Mua ngay</Button></div><ul className="mt-7 grid gap-3 border-y border-[#f2e4e6] py-5 text-sm text-[#665a5a]"><li>✓ Giao trong 2–4 ngày</li><li>✓ Miễn phí vận chuyển từ 699.000đ</li><li>✓ Hỗ trợ đổi size trong 14 ngày</li></ul></section></div>;
}
