import type { Address, Order, Product } from "./types";

const img = (id: string, width = 900, height = 1080) =>
  `https://images.unsplash.com/${id}?w=${width}&h=${height}&fit=crop&auto=format`;

export const products: Product[] = [
  {
    id: 1,
    slug: "dam-bau-linen-that-no",
    name: "Đầm bầu linen thắt nơ",
    category: "maternity",
    categoryLabel: "Đồ bầu",
    price: 549000,
    oldPrice: 649000,
    images: [img("photo-1515886657613-9f3515b0c78f"), img("photo-1496747611176-843222e1e57c"), img("photo-1539109136881-3be0616acf4b")],
    badge: "Bán chạy",
    tone: "#e8d4c9",
    colors: [{ name: "Be tự nhiên", value: "#d7c5ae" }, { name: "Xanh sage", value: "#9dac98" }],
    sizes: [{ name: "S", stock: 7 }, { name: "M", stock: 12 }, { name: "L", stock: 5 }, { name: "XL", stock: 0 }],
    stage: "3 tháng giữa",
    material: "Linen pha cotton",
    rating: 4.9,
    reviews: 124,
    description: "Dáng đầm suông mềm mại, thoáng nhẹ và linh hoạt theo thay đổi của cơ thể mẹ từ thai kỳ đến sau sinh.",
  },
  {
    id: 2,
    slug: "ao-cho-bu-co-v-mem-mai",
    name: "Áo cho bú cổ V mềm mại",
    category: "postpartum",
    categoryLabel: "Sau sinh & cho bú",
    price: 329000,
    images: [img("photo-1529139574466-a303027c1d8b"), img("photo-1542291026-7eec264c27ff")],
    badge: "Mới về",
    tone: "#d9e2d8",
    colors: [{ name: "Kem", value: "#eee4d8" }, { name: "Hồng đất", value: "#b98286" }],
    sizes: [{ name: "S", stock: 8 }, { name: "M", stock: 11 }, { name: "L", stock: 9 }, { name: "XL", stock: 3 }],
    stage: "Sau sinh",
    material: "Modal cotton",
    rating: 4.8,
    reviews: 86,
    description: "Thiết kế mở ngực kín đáo giúp mẹ cho bé bú thuận tiện, chất vải mát và co giãn nhẹ.",
  },
  {
    id: 3,
    slug: "bo-lien-than-so-sinh-cotton",
    name: "Bộ liền thân sơ sinh cotton",
    category: "newborn",
    categoryLabel: "Đồ sơ sinh",
    price: 239000,
    images: [img("photo-1515488042361-ee00e0ddd4e4"), img("photo-1596870230751-ebdfce98ec42")],
    tone: "#f0dcca",
    colors: [{ name: "Trắng sữa", value: "#f5f1e8" }, { name: "Cam nhạt", value: "#e7b990" }],
    sizes: [{ name: "0–3M", stock: 15 }, { name: "3–6M", stock: 18 }, { name: "6–9M", stock: 6 }],
    stage: "0–9 tháng",
    material: "Cotton hữu cơ",
    rating: 4.9,
    reviews: 203,
    description: "Cotton hữu cơ mềm lành, khuy bấm tiện thay tã và đường may phẳng bảo vệ làn da nhạy cảm của bé.",
  },
  {
    id: 4,
    slug: "ao-bau-dang-suong-everyday",
    name: "Áo bầu dáng suông Everyday",
    category: "maternity",
    categoryLabel: "Đồ bầu",
    price: 389000,
    images: [img("photo-1496747611176-843222e1e57c"), img("photo-1539109136881-3be0616acf4b")],
    tone: "#dfcfcb",
    colors: [{ name: "Hồng phấn", value: "#d9b4b6" }, { name: "Đen", value: "#3f3b3c" }],
    sizes: [{ name: "S", stock: 2 }, { name: "M", stock: 10 }, { name: "L", stock: 8 }, { name: "XL", stock: 4 }],
    stage: "3 tháng đầu",
    material: "Cotton co giãn",
    rating: 4.7,
    reviews: 62,
    description: "Phom suông tối giản dễ phối đồ, phần bụng rộng vừa đủ để đồng hành cùng mẹ trong thai kỳ.",
  },
  {
    id: 5,
    slug: "quan-bau-cong-so-co-gian",
    name: "Quần bầu công sở co giãn",
    category: "maternity",
    categoryLabel: "Đồ bầu",
    price: 459000,
    oldPrice: 519000,
    images: [img("photo-1594633312681-425c7b97ccd1"), img("photo-1506629082955-511b1aa562c8")],
    badge: "-12%",
    tone: "#ddd8d0",
    colors: [{ name: "Đen", value: "#332f30" }, { name: "Be", value: "#c6b89f" }],
    sizes: [{ name: "M", stock: 9 }, { name: "L", stock: 7 }, { name: "XL", stock: 5 }],
    stage: "3 tháng cuối",
    material: "Rayon spandex",
    rating: 4.8,
    reviews: 91,
    description: "Cạp bụng nâng đỡ nhẹ, phom đứng thanh lịch phù hợp đi làm và gặp gỡ hàng ngày.",
  },
  {
    id: 6,
    slug: "khan-quan-so-sinh-organic",
    name: "Khăn quấn sơ sinh organic",
    category: "newborn",
    categoryLabel: "Đồ sơ sinh",
    price: 189000,
    images: [img("photo-1544126592-807ade215a0b"), img("photo-1578662996442-48f60103fc96")],
    badge: "Organic",
    tone: "#e9e0d3",
    colors: [{ name: "Kem", value: "#e9dfcc" }, { name: "Xanh nhạt", value: "#bfced0" }],
    sizes: [{ name: "Freesize", stock: 21 }],
    stage: "0–6 tháng",
    material: "Muslin organic",
    rating: 4.9,
    reviews: 146,
    description: "Khăn muslin bốn lớp thoáng khí, mềm hơn sau mỗi lần giặt và đa năng khi chăm bé.",
  },
  {
    id: 7,
    slug: "goi-nang-do-da-nang",
    name: "Gối nâng đỡ đa năng cho mẹ",
    category: "accessories",
    categoryLabel: "Phụ kiện",
    price: 699000,
    images: [img("photo-1584302179602-e4c3d3fd629d"), img("photo-1586023492125-27b2c045efd7")],
    tone: "#ded8cf",
    colors: [{ name: "Kem", value: "#ddd1bf" }],
    sizes: [{ name: "Freesize", stock: 7 }],
    stage: "Thai kỳ & sau sinh",
    material: "Cotton, bông microfiber",
    rating: 4.7,
    reviews: 45,
    description: "Nâng đỡ bụng, lưng và chân khi ngủ; có thể dùng làm gối hỗ trợ cho bé bú sau sinh.",
  },
  {
    id: 8,
    slug: "combo-chao-doi-be-yeu",
    name: "Combo Chào đời bé yêu",
    category: "gift",
    categoryLabel: "Combo quà tặng",
    price: 899000,
    oldPrice: 1099000,
    images: [img("photo-1601979031925-424e53b6caaa"), img("photo-1519689680058-324335c77eba")],
    badge: "Tiết kiệm 18%",
    tone: "#e5d8d0",
    colors: [{ name: "Trung tính", value: "#d7c8b9" }],
    sizes: [{ name: "0–3M", stock: 10 }, { name: "3–6M", stock: 8 }],
    stage: "0–6 tháng",
    material: "Cotton hữu cơ",
    rating: 5,
    reviews: 38,
    description: "Bộ quà tặng gồm bodysuit, khăn quấn, mũ, bao tay chân và thiệp chúc mừng trong hộp An An.",
  },
];

export const defaultAddress: Address = {
  id: 1,
  fullName: "Nguyễn Minh Anh",
  phone: "0901234567",
  email: "minhanh@email.com",
  province: "Hồ Chí Minh",
  district: "Quận 3",
  ward: "Phường Võ Thị Sáu",
  line1: "18 Võ Văn Tần",
  isDefault: true,
};

export const seedOrders: Order[] = [
  {
    code: "AN24082718",
    createdAt: "27/08/2026",
    status: "shipping",
    paymentStatus: "unpaid",
    items: [{ productId: 1, size: "M", color: "Be tự nhiên", quantity: 1 }],
    total: 579000,
    customer: "Nguyễn Minh Anh",
    address: "18 Võ Văn Tần, Phường Võ Thị Sáu, Quận 3, Hồ Chí Minh",
    payment: "Thanh toán khi nhận hàng",
    shipping: "Giao hàng tiêu chuẩn",
  },
  {
    code: "AN24081907",
    createdAt: "19/08/2026",
    status: "delivered",
    paymentStatus: "paid",
    items: [{ productId: 3, size: "0–3M", color: "Trắng sữa", quantity: 2 }],
    total: 478000,
    customer: "Nguyễn Minh Anh",
    address: "18 Võ Văn Tần, Phường Võ Thị Sáu, Quận 3, Hồ Chí Minh",
    payment: "MoMo",
    shipping: "Giao hàng nhanh",
  },
];

export const categoryLabels: Record<Product["category"], string> = {
  maternity: "Đồ bầu",
  postpartum: "Sau sinh & cho bú",
  newborn: "Đồ sơ sinh",
  accessories: "Phụ kiện",
  gift: "Combo quà tặng",
};

export const formatMoney = (value: number) => `${new Intl.NumberFormat("vi-VN").format(value)}₫`;
