"use client";

import { useMemo, useState } from "react";
import type { AdminResource, AdminRow } from "@/lib/admin/admin-data";

const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

export function AdminResourcePage({ resource, resourceKey }: { resource: AdminResource; resourceKey: string }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("Tất cả");
  const [selected, setSelected] = useState<AdminRow | null>(null);
  const [creating, setCreating] = useState(false);
  const shown = useMemo(() => resource.rows.filter((item) => {
    const matchesQuery = normalize([...item.cells, item.status].join(" ")).includes(normalize(query));
    return matchesQuery && (status === "Tất cả" || item.status === status);
  }), [query, resource.rows, status]);

  return (
    <section aria-labelledby={`${resourceKey}-title`} data-testid={`admin-${resourceKey}-page`}>
      <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.2em] text-rose-700">An An Backoffice</p><h1 id={`${resourceKey}-title`} className="text-2xl font-semibold tracking-tight sm:text-3xl">{resource.title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">{resource.description}</p></div>
        {resource.createLabel && <button type="button" onClick={() => setCreating(true)} className="min-h-11 rounded-xl bg-[#b06b75] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#245c4c] focus:outline-none focus:ring-2 focus:ring-emerald-700 focus:ring-offset-2" data-testid={`${resourceKey}-create`}>+ {resource.createLabel}</button>}
      </div>
      <div className="mb-4 grid gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:grid-cols-[minmax(0,1fr)_220px]">
        <label><span className="sr-only">Tìm trong {resource.title}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Tìm trong ${resource.title.toLowerCase()}…`} className="min-h-11 w-full rounded-xl border border-slate-300 px-4 text-sm outline-none focus:border-rose-700 focus:ring-2 focus:ring-emerald-100" data-testid={`${resourceKey}-search`} /></label>
        <label><span className="sr-only">Lọc theo trạng thái</span><select value={status} onChange={(event) => setStatus(event.target.value)} className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm focus:border-rose-700 focus:ring-2 focus:ring-emerald-100" data-testid={`${resourceKey}-status-filter`}><option>Tất cả</option>{resource.statuses.map((item) => <option key={item}>{item}</option>)}</select></label>
      </div>
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        {shown.length ? <div className="overflow-x-auto"><table className="w-full min-w-[820px] border-collapse text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{resource.headers.map((header) => <th key={header} scope="col" className="px-5 py-3 font-semibold">{header}</th>)}<th scope="col" className="px-5 py-3 font-semibold">Trạng thái</th><th scope="col" className="px-5 py-3"><span className="sr-only">Thao tác</span></th></tr></thead><tbody className="divide-y divide-slate-100">{shown.map((item) => <tr key={item.id} className="hover:bg-rose-50/40">{item.cells.map((cell, index) => <td key={`${item.id}-${index}`} className={`px-5 py-4 ${index === 0 ? "font-medium text-slate-900" : "text-slate-600"}`}>{cell}</td>)}<td className="px-5 py-4"><span className="inline-flex rounded-full bg-rose-50 px-2.5 py-1 text-xs font-medium text-rose-800">{item.status}</span></td><td className="px-5 py-4 text-right"><button type="button" onClick={() => setSelected(item)} className="min-h-10 rounded-lg px-3 text-sm font-semibold text-rose-800 hover:bg-rose-50" aria-label={`Xem chi tiết ${item.cells[0]}`} data-testid={`${resourceKey}-detail-${item.id}`}>Chi tiết</button></td></tr>)}</tbody></table></div> : <div className="px-6 py-16 text-center" role="status" data-testid={`${resourceKey}-empty`}><p className="font-medium">Không tìm thấy dữ liệu phù hợp</p><p className="mt-1 text-sm text-slate-500">Hãy thay đổi từ khóa hoặc bộ lọc trạng thái.</p><button type="button" onClick={() => { setQuery(""); setStatus("Tất cả"); }} className="mt-4 rounded-lg px-4 py-2 text-sm font-semibold text-rose-800 hover:bg-rose-50">Xóa bộ lọc</button></div>}
      </div>
      {selected && <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/30" role="presentation" onMouseDown={(event) => event.currentTarget === event.target && setSelected(null)}><aside role="dialog" aria-modal="true" aria-label="Chi tiết" className="h-full w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl"><div className="mb-6 flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-rose-700">Chi tiết</p><h2 id="detail-title" className="mt-1 text-xl font-semibold">{selected.cells[0]}</h2></div><button type="button" onClick={() => setSelected(null)} className="min-h-11 min-w-11 rounded-xl border border-slate-200 text-xl" aria-label="Đóng chi tiết">×</button></div><dl className="divide-y divide-slate-100 rounded-2xl border border-slate-200">{selected.detail.map(([label, value]) => <div key={label} className="grid gap-1 p-4 sm:grid-cols-[140px_1fr]"><dt className="text-sm text-slate-500">{label}</dt><dd className="text-sm font-medium text-slate-900">{value}</dd></div>)}</dl><div className="mt-6 flex flex-wrap gap-3"><button type="button" className="min-h-11 rounded-xl bg-[#b06b75] px-5 text-sm font-semibold text-white">Cập nhật</button><button type="button" onClick={() => setSelected(null)} className="min-h-11 rounded-xl border border-slate-300 px-5 text-sm font-semibold">Đóng</button></div></aside></div>}
      {creating && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); setCreating(false); }} role="dialog" aria-modal="true" aria-labelledby="create-title" className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-rose-700">Tạo mới</p><h2 id="create-title" className="mt-1 text-xl font-semibold">{resource.createLabel}</h2></div><button type="button" onClick={() => setCreating(false)} className="min-h-11 min-w-11 rounded-xl border border-slate-200 text-xl" aria-label="Đóng biểu mẫu">×</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Tên / mã<input required className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 px-3" /></label><label className="text-sm font-medium">Trạng thái<select className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3">{resource.statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-medium sm:col-span-2">Ghi chú<textarea rows={4} className="mt-1.5 w-full rounded-xl border border-slate-300 p-3" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setCreating(false)} className="min-h-11 rounded-xl border border-slate-300 px-5 text-sm font-semibold">Hủy</button><button type="submit" className="min-h-11 rounded-xl bg-[#b06b75] px-5 text-sm font-semibold text-white" data-testid={`${resourceKey}-submit`}>Lưu bản nháp</button></div></form></div>}
    </section>
  );
}
