"use client";
import { useCallback, useEffect, useState } from "react";
import { AccessibleDialog } from "./accessible-dialog";

type Row = { id: string; order_code: string; customer_name?: string; reason: string; status: string; requested_at: string };
type Item = { id: string; product_name: string; variant_name?: string; quantity: number; condition?: string; resolution?: string; refund_amount: string };
type Refund = { id: string; status: string; amount: string };
type Detail = Row & { payment_id: string; expected_refund: string; items: Item[]; refunds: Refund[] };
const labels: Record<string,string> = { REQUESTED:"Chờ duyệt",APPROVED:"Đã duyệt",REJECTED:"Từ chối",RECEIVED:"Đã nhận hàng",REFUNDED:"Đã hoàn tiền",CLOSED:"Đã đóng" };
export function ReturnsPageClient(){
  const [rows,setRows]=useState<Row[]>([]); const [selected,setSelected]=useState<Detail|null>(null); const [error,setError]=useState(""); const [note,setNote]=useState(""); const [pending,setPending]=useState(false); const [receipts,setReceipts]=useState<Record<string,{condition:string;resolution:string}>>({});
  const load=useCallback(async()=>{const r=await fetch('/api/admin/returns?pageSize=100');const p=await r.json();if(!r.ok)throw new Error(p.error?.message);setRows(p.data.items)},[]);
  useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Không thể tải dữ liệu"));},[load]);
  const detail=async(id:string)=>{setError("");const r=await fetch(`/api/admin/returns/${id}`);const p=await r.json();if(!r.ok){setError(p.error?.message);return}setSelected(p.data);setReceipts(Object.fromEntries(p.data.items.map((i:Item)=>[i.id,{condition:i.condition||"Nguyên vẹn",resolution:i.resolution||"RESTOCK"}])))};
  const transition=async(status:string)=>{if(!selected)return;setPending(true);setError("");let currentNote = note; if(status==='REJECTED' && !currentNote){currentNote=prompt("Vui lòng nhập lý do từ chối:")||""; if(!currentNote){setPending(false);return;}} const body:Record<string,unknown>={status,adminNote:currentNote||undefined};if(status==='RECEIVED')body.items=selected.items.map(i=>({returnItemId:i.id,...receipts[i.id]}));try{const r=await fetch(`/api/admin/returns/${selected.id}/transition`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.error?.message);setNote('');await load();await detail(selected.id)}catch(e){setError(e instanceof Error?e.message:'Không thể cập nhật')}finally{setPending(false)}};
  const createRefund=async()=>{if(!selected)return;setPending(true);try{const r=await fetch('/api/admin/refunds',{method:'POST',headers:{'content-type':'application/json','idempotency-key':`return-${selected.id}`},body:JSON.stringify({paymentId:selected.payment_id,returnRequestId:selected.id,amount:Number(selected.expected_refund),reason:selected.reason})});const p=await r.json();if(!r.ok)throw new Error(p.error?.message);await detail(selected.id)}catch(e){setError(e instanceof Error?e.message:'Không thể tạo hoàn tiền')}finally{setPending(false)}};
  const completeRefund=async(refundId:string)=>{if(!selected)return;setPending(true);try{const r=await fetch(`/api/admin/refunds/${refundId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'COMPLETE'})});const p=await r.json();if(!r.ok)throw new Error(p.error?.message);await detail(selected.id)}catch(e){setError(e instanceof Error?e.message:'Không thể đối soát hoàn tiền')}finally{setPending(false)}};
  const pendingRefund=selected?.refunds.find(r=>r.status==='PENDING'); const completed=selected?.refunds.some(r=>r.status==='REFUNDED');
  return <section data-testid="admin-returns-page"><h1 className="text-3xl font-semibold">Đổi trả & hoàn tiền</h1><p className="mt-2 text-sm text-slate-600">Duyệt yêu cầu, lập biên bản nhận từng sản phẩm, hoàn kho và đối soát tiền theo giao dịch gốc.</p>{error&&<p role="alert" className="my-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}<div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[720px] text-sm"><thead><tr>{["Đơn hàng","Khách hàng","Lý do","Ngày yêu cầu","Trạng thái",""] .map(h=><th className="p-4 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.id}><td className="p-4 font-semibold">{r.order_code}</td><td className="p-4">{r.customer_name||'—'}</td><td className="p-4">{r.reason}</td><td className="p-4">{new Date(r.requested_at).toLocaleDateString('vi-VN')}</td><td className="p-4">{labels[r.status]}</td><td className="p-4"><button onClick={()=>void detail(r.id)} className="font-semibold text-emerald-800">Xử lý</button></td></tr>)}</tbody></table></div>
  <AccessibleDialog open={Boolean(selected)} title="Xử lý đổi trả" onClose={()=>setSelected(null)} footer={<button className="min-h-11 rounded-xl border px-5" onClick={()=>setSelected(null)}>Đóng</button>}>{selected&&<div className="space-y-4"><p><strong>{selected.order_code}</strong> · {labels[selected.status]}</p>
  
  {selected.status === 'CLOSED' && (
    <div className="rounded-xl bg-slate-50 p-4 border border-slate-200">
      <h4 className="font-semibold mb-2">Thông tin hồ sơ (Đã đóng)</h4>
      <p className="text-sm mb-1"><strong>Kết quả:</strong> {selected.items.some(i => i.condition) ? <span className="text-emerald-700">Đã chấp nhận (Hoàn tiền/Đổi trả)</span> : <span className="text-red-700">Đã từ chối</span>}</p>
      <p className="text-sm mb-1"><strong>Lý do của khách hàng:</strong> {selected.reason}</p>
      <p className="text-sm"><strong>Ghi chú của Admin:</strong> {(selected as any).admin_note || "Không có ghi chú"}</p>
    </div>
  )}

  <ul className="divide-y rounded-xl border">{selected.items.map(item=><li className="p-4" key={item.id}><strong>{item.product_name}</strong> · {item.variant_name} × {item.quantity}<p className="text-sm">Dự kiến hoàn: {Number(item.refund_amount).toLocaleString('vi-VN')} ₫</p>{selected.status==='APPROVED'&&<div className="mt-3 grid gap-2 sm:grid-cols-2"><input aria-label="Tình trạng" className="rounded-lg border p-2" value={receipts[item.id]?.condition||''} onChange={e=>setReceipts(v=>({...v,[item.id]:{...v[item.id],condition:e.target.value}}))}/><select aria-label="Quyết định kho" className="rounded-lg border p-2" value={receipts[item.id]?.resolution||'RESTOCK'} onChange={e=>setReceipts(v=>({...v,[item.id]:{...v[item.id],resolution:e.target.value}}))}><option value="RESTOCK">Hoàn kho</option><option value="DISPOSE">Không hoàn kho</option></select></div>}</li>)}</ul><label className="block text-sm font-medium">Ghi chú xử lý<textarea value={note} onChange={e=>setNote(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><div className="flex flex-wrap gap-2">{selected.status==='REQUESTED'&&<><button disabled={pending} onClick={()=>void transition('APPROVED')} className="rounded-xl bg-emerald-800 px-4 py-3 text-white">Duyệt</button><button disabled={pending} onClick={()=>void transition('REJECTED')} className="rounded-xl bg-red-700 px-4 py-3 text-white">Từ chối</button></>}{selected.status==='APPROVED'&&<button disabled={pending} onClick={()=>void transition('RECEIVED')} className="rounded-xl bg-emerald-800 px-4 py-3 text-white">Xác nhận đã nhận hàng</button>}{selected.status==='RECEIVED'&&<button disabled={pending} onClick={()=>void transition('REFUNDED')} className="rounded-xl bg-emerald-800 px-4 py-3 text-white">Đóng là đã hoàn tiền</button>}{['REFUNDED','REJECTED'].includes(selected.status)&&<button disabled={pending} onClick={()=>void transition('CLOSED')} className="rounded-xl border px-4 py-3">Đóng hồ sơ</button>}</div></div>}</AccessibleDialog></section>
}