"use client";

import { useState } from "react";

export function SettingsPage() {
  const [saved, setSaved] = useState(false);
  return <section aria-labelledby="settings-title" data-testid="admin-settings-page"><div className="mb-6"><p className="mb-1 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-700">Cấu hình hệ thống</p><h1 id="settings-title" className="text-2xl font-semibold sm:text-3xl">Cài đặt cửa hàng</h1><p className="mt-2 text-sm text-slate-600">Thông tin liên hệ, vận hành và cấu hình đặt hàng.</p></div>{saved && <div role="status" className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Đã lưu cài đặt. Thay đổi đã được ghi vào nhật ký kiểm toán.</div>}<form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="space-y-6"><fieldset className="rounded-2xl border border-slate-200 bg-white p-5"><legend className="px-2 font-semibold">Thông tin cửa hàng</legend><div className="grid gap-4 sm:grid-cols-2"><Field label="Tên cửa hàng" value="An An Shop" /><Field label="Email hỗ trợ" value="hello@ananshop.vn" type="email" /><Field label="Hotline" value="1900 6868" /><Field label="Múi giờ" value="Asia/Ho_Chi_Minh" /><label className="text-sm font-medium sm:col-span-2">Địa chỉ<textarea defaultValue="18 Võ Văn Tần, Quận 3, TP.HCM" rows={3} className="mt-1.5 w-full rounded-xl border border-slate-300 p-3" /></label></div></fieldset><fieldset className="rounded-2xl border border-slate-200 bg-white p-5"><legend className="px-2 font-semibold">Đơn hàng & tồn kho</legend><div className="grid gap-4 sm:grid-cols-2"><Field label="Thời gian giữ tồn (phút)" value="15" type="number" /><Field label="Số ngày cho phép đổi trả" value="14" type="number" /><label className="flex items-start gap-3 rounded-xl border border-slate-200 p-4 text-sm"><input type="checkbox" defaultChecked className="mt-1 h-4 w-4" /><span><strong className="block">Cho phép COD</strong><span className="text-slate-500">Khách có thể thanh toán khi nhận hàng.</span></span></label><label className="flex items-start gap-3 rounded-xl border border-slate-200 p-4 text-sm"><input type="checkbox" defaultChecked className="mt-1 h-4 w-4" /><span><strong className="block">Cảnh báo tồn thấp</strong><span className="text-slate-500">Gửi thông báo cho nhân viên kho.</span></span></label></div></fieldset><div className="flex justify-end"><button type="submit" className="min-h-11 rounded-xl bg-[#173c32] px-6 text-sm font-semibold text-white" data-testid="settings-save">Lưu cài đặt</button></div></form></section>;
}

function Field({ label, value, type = "text" }: { label: string; value: string; type?: string }) { return <label className="text-sm font-medium">{label}<input type={type} defaultValue={value} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 px-3" /></label>; }
